Writable:
  LogLevel: DEBUG
  Reading:
    ReadingUnits: true
  Telemetry:
    Metrics:
      # All service's custom metric names must be present in this list. All common metric names are in the Common Config
      ReadCommandsExecuted: true
Service:
  Host: 'localhost'
  Port: # 59994 for testing

Device:
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: './res/profiles'
  DevicesDir: './res/devices'
